hash-format = "sha256"

[[files]]
file = "mods/bee-angry-est.toml"
hash = "2435239d167a4145774414ebba545b0d4276428315f3b27dfe0695326666167b"
metafile = true

[[files]]
file = "mods/better-op.toml"
hash = "764edbf08b5cf0e4f1b7a3034f06b81e6abf3a14848a5d9dd70d21f77dc27416"
metafile = true

[[files]]
file = "mods/bits-and-chisels.toml"
hash = "1d873734f2e3964fe45222bb1c7788cb6e91c08210d01853dd945e499d65ad34"
metafile = true

[[files]]
file = "mods/bouncy-life.toml"
hash = "9626f63fe6e9d18190f2a6e5282d6797598ee88d84aeffa4c6d456a43b4a39ee"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "198b707765f67dd2baa93ad0c52f5a55411b8301c34f00764dd3f0a3f4eb6098"
metafile = true

[[files]]
file = "mods/consistencyplus.toml"
hash = "48ca264f78795c8758273cb9d080663825dee27a0850b7362d5b0373b8c350af"
metafile = true

[[files]]
file = "mods/defibrillator.toml"
hash = "568d2f5158c49df5763750fbe9049e88cd5837a730c1fbaca9119aeee62d94b6"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "d968b237fe5395af954f1e65ec073c3b84b1f7b71676222efa0917ae781df478"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "6ea9be1422cb6fab23483546c06e94753412e9642099f46ab6a316ccf2c8403b"
metafile = true

[[files]]
file = "mods/fabric-loot-crates.toml"
hash = "33f5d8fb0515c29661b08f22ba03eb303fce786f1fd1961b1336407b7d5fffc9"
metafile = true

[[files]]
file = "mods/fabric-permissions-api.toml"
hash = "c4657471350d384624b4b42fd47a1a1f2b34e88686f23e0dc8a196b1a4d60277"
metafile = true

[[files]]
file = "mods/fabric-zones.toml"
hash = "343c389e78404ae2b5332272ef0902d09ab7ae8f6033ca8a2cc23519321a7edd"
metafile = true

[[files]]
file = "mods/fabrichomes.toml"
hash = "0238a0b7787c35c352311e311f040ccd31829ccd8cd76056ece43e2a852d978c"
metafile = true

[[files]]
file = "mods/fabrictpa.toml"
hash = "8b65dae015b9a8f1212cf61a85454640c798b2d08241f1495161a2f4ee655bd1"
metafile = true

[[files]]
file = "mods/fabricwarps.toml"
hash = "f6f563bc1fbf1ef7cbe38735da8cacaa5192064420ba4f9527aa3b155be237d7"
metafile = true

[[files]]
file = "mods/fritater.toml"
hash = "1d64a817a626be1279af051f0f10726e71d0d32dd3fa5a3461961b7d095a1f59"
metafile = true

[[files]]
file = "mods/geckolib-fabric.toml"
hash = "a397d241ff746dfa4863525b4284d55927a6421e544e3ca941e1af3ba84e0411"
metafile = true

[[files]]
file = "mods/gift-it.toml"
hash = "11195c4da6d954c2d7db647140c61f950237fb1a772e0943cfd49f7d51fbdff8"
metafile = true

[[files]]
file = "mods/globalspawn.toml"
hash = "8d09bab6352bcb557d6af209b178c70f5794c8935f6e281b0e6f8324aa5ae426"
metafile = true

[[files]]
file = "mods/healthcare.toml"
hash = "ea499f3213e2f179d5fe2e33ad0bbf9803b4970cf9b259ffef1021f025f8b762"
metafile = true

[[files]]
file = "mods/immigistics.toml"
hash = "aa0a25de9b074612e6b172e2542eb7f4bdc331472d0bfd55f9af097171c6a0da"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "a26234f77b223145a1fc98416a49d6ce1e7a9f2793788604a9103abb5e19506c"
metafile = true

[[files]]
file = "mods/knowyourknot-enderporter.toml"
hash = "5878b4d1256be5ccb9e1eb8b537cb448ccf7ecb3b20aae46dd15d064fa37f40c"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "b47b2d6351087ad346299faff6daca6047870901fa3ce4c9a79bda719db0a74b"
metafile = true

[[files]]
file = "mods/liltaterreloaded.toml"
hash = "3e39a7cfe8d287eaf8f7eb42f2208b9b9c48df703b5a11ac97ec15e069e09416"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "2034730274e8d3fa905b0c960b7d8f04f1241fb8c908a34272970dfba0c2a6cc"
metafile = true

[[files]]
file = "mods/luckperms.toml"
hash = "68fc8ec3c21073bb09659c3719ceb30b54f60d2737b5dba35956ba78d0fa7a4c"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "cbc1c51c63ad8de8978eec90d85522d429391ce43d017a3bbe6d6da3d20b2bb1"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "9a754d5a9a2307b4811f3ec51867f3eae452a843273abf294e6f734c77c79ec2"
metafile = true

[[files]]
file = "mods/now-playing.toml"
hash = "df37ce8bb504facf809bd49ab2bee35ce514626fa492f6c18f4c0a86c17b608f"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "a0d25fe86a7274ef247c69309772f3ae05cce6f58903162cfda99c0dd4bc8265"
metafile = true

[[files]]
file = "mods/pingspam.toml"
hash = "cc6acea146761b60b9f2bb1f01e3125cd4000ddd2a7cfcb58f6e490cfee6dde0"
metafile = true

[[files]]
file = "mods/rats-mischief.toml"
hash = "24d2f424e00bf9eb04533bcfd96455d26f13a47b43597a03cda28e060bd51235"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
hash = "be16719db2ee9f649d8767e310d66b34e03b2458831c25b9675cbe3db9d79fc5"
metafile = true

[[files]]
file = "mods/simple-angel-ring.toml"
hash = "beda7b17d00d6e384f909200899deb9ca0c740e1d000bf00e9bd2dcff80f5628"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "9edc0aa7b696d1303803fc1ea6ee1ab4a48e4ca688fdba1ff696b7ee35409810"
metafile = true

[[files]]
file = "mods/starry-skies.toml"
hash = "4c32b0d6b58933f9b00c861e649eeae1b9885a4039bd3c80cda59b27ebe58cf7"
metafile = true

[[files]]
file = "mods/territorial.toml"
hash = "54655dc41dae18cae6e54c5e1ddfcf36bebe58519bfc693eb9d1a93f1bf57b69"
metafile = true

[[files]]
file = "mods/through-the-looking-glass.toml"
hash = "544c3f4281581d40ddb2b334984898e53bef6e6d2ecf46e59a173cbced9e59bc"
metafile = true

[[files]]
file = "mods/tiny-trash-can.toml"
hash = "1851f53a53b366d470ca8bdae092867bac921d76dbeb4cad8b3e46502a37b717"
metafile = true

[[files]]
file = "mods/toms-server-utils.toml"
hash = "987f0635cde62a87395f23fae6197879ca74775ed315c965a9dab93471fa82b9"
metafile = true

[[files]]
file = "mods/underfabric.toml"
hash = "0a79d00892bd186141aa3f93775f25b82d486e686d42fa834df7280ae9d20fca"
metafile = true

[[files]]
file = "mods/world-blender-fabric.toml"
hash = "7716bf604aa9bfe6226c364f72657cfdbc8b1bcc48525bacebf030555d479336"
metafile = true

[[files]]
file = "mods/world-border-fix.toml"
hash = "8f5abfd3187abdee74dfc914878fe01415825e7ab47e13a3def8a0d27d9b256c"
metafile = true
