name = "FabricWarps"
filename = "FabricWarps-0.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3279/358/FabricWarps-0.2.1.jar"
hash-format = "murmur2"
hash = "3008964282"

[update]
[update.curseforge]
file-id = 3279358
project-id = 433362
release-channel = "beta"
