name = "FabricWarps"
filename = "FabricWarps-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3162/202/FabricWarps-0.2.0.jar"
hash-format = "murmur2"
hash = "3305719501"

[update]
[update.curseforge]
file-id = 3162202
project-id = 433362
release-channel = "beta"
