name = "LuckPerms"
filename = "LuckPerms-Fabric-5.3.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3245/738/LuckPerms-Fabric-5.3.9.jar"
hash-format = "murmur2"
hash = "304666061"

[update]
[update.curseforge]
file-id = 3245738
project-id = 431733
release-channel = "beta"
